#!/usr/bin/env python3
"""
spv_to_cpp.py - emit a C/C++ source file containing a Vulkan SPIR-V blob
as a uint32_t array.

Usage:
    spv_to_cpp.py <spv_file> <array_name> [<spv_file2> <array_name2> ...] > out.cpp

The output is one file containing every blob. Each blob gets two symbols:
    extern "C" const uint32_t <name>[]    -- the SPIR-V words
    extern "C" const size_t      <name>_size  -- byte size (== words * 4)

The C++ file has a header guard and is safe to compile in any TU.
"""

import sys
import os
import pathlib


def words_from_spv(path: pathlib.Path) -> bytes:
    raw = path.read_bytes()
    # SPIR-V magic number is 0x07230203 in little-endian, i.e. the file must
    # be a multiple of 4 bytes.
    if len(raw) % 4 != 0:
        raise ValueError(f"{path}: SPIR-V size {len(raw)} is not a multiple of 4")
    magic = int.from_bytes(raw[:4], "little")
    if magic != 0x07230203:
        raise ValueError(f"{path}: bad SPIR-V magic 0x{magic:08x}")
    return raw


def emit_word_array(name: str, raw: bytes) -> str:
    words = []
    for i in range(0, len(raw), 4):
        words.append("0x%08x" % int.from_bytes(raw[i:i + 4], "little"))
    lines = []
    for i in range(0, len(words), 8):
        lines.append("    " + ", ".join(words[i:i + 8]) + ",")
    body = "\n".join(lines)
    array_decl = 'extern "C" const uint32_t ' + name + "[] = {\n" + body + "\n};\n"
    size_decl = 'extern "C" const size_t ' + name + "_size = sizeof(" + name + ");\n"
    return array_decl + size_decl


def main(argv: list) -> int:
    if len(argv) < 3 or (len(argv) - 1) % 2 != 0:
        print(__doc__, file=sys.stderr)
        return 2

    pairs = list(zip(argv[1::2], argv[2::2]))
    parts = ["// Auto-generated by spv_to_cpp.py. Do not edit.\n",
             "#include <cstddef>\n",
             "#include <cstdint>\n",
             "\n"]

    for path_str, name in pairs:
        path = pathlib.Path(path_str)
        if not path.is_file():
            print(f"{path}: not found", file=sys.stderr)
            return 1
        raw = words_from_spv(path)
        parts.append(f"// {os.path.basename(path_str)} ({len(raw)} bytes, {len(raw) // 4} words)\n")
        parts.append(emit_word_array(name, raw))
        parts.append("\n")

    sys.stdout.write("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
